const COMPANY_NAMES: Record<string, string> = {
  AAPL: "Apple Inc.",
  MSFT: "Microsoft Corp.",
  NVDA: "NVIDIA Corp.",
  META: "Meta Platforms",
  SOFI: "SoFi Technologies",
  HOOD: "Robinhood Markets",
  TSLA: "Tesla Inc.",
  AMZN: "Amazon.com Inc.",
  GOOGL: "Alphabet Inc.",
  GOOG: "Alphabet Inc.",
  NFLX: "Netflix Inc.",
  AMD: "Advanced Micro Devices",
  INTC: "Intel Corp.",
  QCOM: "Qualcomm Inc.",
  AVGO: "Broadcom Inc.",
  TSM: "Taiwan Semiconductor",
  ASML: "ASML Holding",
  BABA: "Alibaba Group",
  JPM: "JPMorgan Chase",
  BAC: "Bank of America",
  GS: "Goldman Sachs",
  MS: "Morgan Stanley",
  V: "Visa Inc.",
  MA: "Mastercard Inc.",
  PYPL: "PayPal Holdings",
  SQ: "Block Inc.",
  COIN: "Coinbase Global",
  MSTR: "MicroStrategy",
  DIS: "Walt Disney Co.",
  NKLA: "Nikola Corp.",
  RIVN: "Rivian Automotive",
  LCID: "Lucid Group",
  F: "Ford Motor Co.",
  GM: "General Motors",
  NIO: "NIO Inc.",
  UBER: "Uber Technologies",
  LYFT: "Lyft Inc.",
  ABNB: "Airbnb Inc.",
  SHOP: "Shopify Inc.",
  PLTR: "Palantir Technologies",
  SNOW: "Snowflake Inc.",
  CRWD: "CrowdStrike Holdings",
  ZS: "Zscaler Inc.",
  PANW: "Palo Alto Networks",
  NET: "Cloudflare Inc.",
  DDOG: "Datadog Inc.",
  MDB: "MongoDB Inc.",
  OKTA: "Okta Inc.",
  ZM: "Zoom Video Comm.",
  SPOT: "Spotify Technology",
  RBLX: "Roblox Corp.",
  U: "Unity Software",
  PINS: "Pinterest Inc.",
  SNAP: "Snap Inc.",
  X: "X Holdings",
  TWTR: "Twitter Inc.",
  WMT: "Walmart Inc.",
  TGT: "Target Corp.",
  COST: "Costco Wholesale",
  HD: "Home Depot Inc.",
  LOW: "Lowe's Companies",
  MCD: "McDonald's Corp.",
  SBUX: "Starbucks Corp.",
  NKE: "Nike Inc.",
  PFE: "Pfizer Inc.",
  JNJ: "Johnson & Johnson",
  MRNA: "Moderna Inc.",
  BNTX: "BioNTech SE",
  LLY: "Eli Lilly and Co.",
  BA: "Boeing Co.",
  CAT: "Caterpillar Inc.",
  GE: "GE Aerospace",
  XOM: "ExxonMobil Corp.",
  CVX: "Chevron Corp.",
  T: "AT&T Inc.",
  VZ: "Verizon Comm.",
  TMUS: "T-Mobile US",
  SPY: "SPDR S&P 500 ETF",
  QQQ: "Invesco QQQ ETF",
  IWM: "iShares Russell 2000",
  BRK: "Berkshire Hathaway",
  BRKB: "Berkshire Hathaway B",
  ORCL: "Oracle Corp.",
  CRM: "Salesforce Inc.",
  NOW: "ServiceNow Inc.",
  ADBE: "Adobe Inc.",
  INTU: "Intuit Inc.",
};

export function getCompanyName(ticker: string): string {
  return COMPANY_NAMES[ticker.toUpperCase()] ?? "";
}
